name: E2E Tests

on:
  push:
  pull_request:

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install the latest version of kind
        run: |
          make dep-install-kind
          make dep-install-kubectl

      - name: Verify local versions
        run: |
          bin/kind version
          bin/kubectl version

      - name: Setup cluster
        run: |
          make kind-setup
          make kind-load-image

      - name: Running Test e2e
        run: |
          go mod tidy
          make test-e2e
